---
- name: THW 3 Provisioning Compute Resources
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    project: nodal-kite-225016
    region: europe-west1
    zone: europe-west1-b
    inst_count: 3
  tasks:

    - name: Virtual Private Cloud Network
      gce_net:
          name: kubernetes-the-hard-way
          mode: custom
          subnet_name: kubernetes
          subnet_region: "{{ region }}"
          ipv4_range: 10.240.0.0/24

    - name: Firewall external
      gce_net:
        name: kubernetes-the-hard-way
        fwname: kubernetes-the-hard-way-allow-external
        allowed: tcp;udp;icmp
        src_range: [ '10.240.0.0/24', '10.200.0.0/16' ]

    - name: Firewall internal
      gce_net:
        name: kubernetes-the-hard-way
        fwname: kubernetes-the-hard-way-allow-internal
        allowed: tcp:22;tcp:6443;icmp
        src_range: [ '0.0.0.0/0' ]

    - name: Regional external IP
      gce_eip:
        name: kubernetes-the-hard-way
        region: "{{ region }}"

    - name: Kubernetes Controllers
      gce:
        name: "controller-{{ item }}"
        zone: "{{ zone }}"
        metadata: '{"sshKeys":"appuser:{{ lookup("file", "~/.ssh/appuser.pub") }}"}'
        disk_size: 200
        ip_forward: true
        external_projects: ubuntu-os-cloud
        image_family: ubuntu-1804-lts
        machine_type: n1-standard-1
        service_account_permissions:
          - compute-rw
          - storage-ro
          - service-management
          - service-control
          - logging-write
          - monitoring
        network: kubernetes-the-hard-way
        subnetwork: kubernetes
        tags: kubernetes-the-hard-way,controller
      with_sequence: start=0 end={{ inst_count - 1 }}

    - name: Kubernetes Workers
      gce:
        name: "worker-{{ item }}"
        zone: "{{ zone }}"
        metadata: '{"sshKeys":"appuser:{{ lookup("file", "~/.ssh/appuser.pub") }}","pod-cidr":"10.200.{{ item }}.0/24"}'
        disk_size: 200
        ip_forward: true
        external_projects: ubuntu-os-cloud
        image_family: ubuntu-1804-lts
        machine_type: n1-standard-1
        service_account_permissions:
          - compute-rw
          - storage-ro
          - service-management
          - service-control
          - logging-write
          - monitoring
        network: kubernetes-the-hard-way
        subnetwork: kubernetes
        tags: kubernetes-the-hard-way,worker
      with_sequence: start=0 end={{ inst_count - 1 }}
