image: ruby:2.4.2

stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'

build_job:
  stage: build
  image: docker:stable
  before_script:
    - docker info
  script:
    - echo 'Building'
    - echo ${DOCKER_PASS} | docker login --username ${DOCKER_LOGIN} --password-stdin
    - cd docker-monolith
    - docker build -t ${DOCKER_LOGIN}/reddit:${CI_COMMIT_SHA} .
    - docker push ${DOCKER_LOGIN}/reddit:${CI_COMMIT_SHA}

test_unit_job:
  stage: test
  services:
    - mongo:latest
  before_script:
    - cd reddit
    - bundle install
  script:
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

branch_review:
  stage: review
  variables:
    DM_IP: ""
  image:
    name: google/cloud-sdk:latest
  before_script:
    - echo $GC_CRED > ${HOME}/cred.json
    - export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/cred.json
    - gcloud auth activate-service-account --key-file=${HOME}/cred.json
    - gcloud config set project $GC_PROJECT
    - |
      base=https://github.com/docker/machine/releases/download/v0.16.0 &&
        curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine &&
        install /tmp/docker-machine /usr/local/bin/docker-machine
    - docker-machine version
    - |
      docker-machine create \
        --driver google \
        --google-project ${GC_PROJECT} \
        --google-zone ${GC_ZONE} \
        --google-machine-type f1-micro \
        ${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}
    - DM_IP=$(docker-machine ip "${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}")
    - echo "docker-machine ip - ${DM_IP}"
    - eval $(docker-machine env --shell sh "${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}")
  script:
    - echo "Deploy a review app"
    - docker run -d -p 9292:9292 ${DOCKER_LOGIN}/reddit:${CI_COMMIT_SHA}
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://${CI_ENVIRONMENT_SLUG}.example.com:9292
    on_stop: stop_branch_review
  only:
    - branches
  except:
    - master

stop_branch_review:
  stage: review
  image:
    name: google/cloud-sdk:latest
  variables:
    GIT_STRATEGY: none
  script:
    - echo "Remove review app"
    - echo $GC_CRED > ${HOME}/cred.json
    - gcloud auth activate-service-account --key-file=${HOME}/cred.json
    - gcloud config set project $GC_PROJECT
    - gcloud compute instances delete --quiet "${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}" --zone=${GC_ZONE}
  when: manual
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    action: stop
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com
