dist: trusty
sudo: required
language: bash

before_install:
 - curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh | bash

notifications:
  slack:
    secure: BkHu0MBbt4SR9op3CR1vlvo8pYlQyuZSLxOgZMMGnicCslno77ehnN6iiGueB49l/muXIJc5LdK/kGsnraxluogdnV0C0vtkxNwr9uZY+mHlIvhwi1uefw8dGnyaUIdGmRCrHz47a7gQhnTrgPm4tudCC9Gw08yyqqZQWhc+20604E8xfNGQMHXvOFQHHpqrGJZN6p/Cve/vwg4eF5+flSwCsRLKS+gRhdT9T57SrV+TwYoWnvyDwoeDecIb+w5reBJJug980NJI0hSaW3zMmmxX+zIZduPrdyOzPDgHrbpBPjpZdBqRHPfOx9IJ+MooAieQ3f36/aRxz5X3JfeLy7D0xVKJ3HxY5iHwsbrTMjDHmhqO1n7GGE8pyk5lTY9+cbkJQbwTjHuI5b5AbJK8JRs6TLgSWtRPlSUL3mAN178/Fd+97XUyvxzXqMUhXRhJ+GyJ7+6opuR7TbR/MMEb+4zAVJ8AbZRA8WyFUe2llGDKo7vrT1aY5TWWJIc0RWRbbMkzUTG+S6fcEQbSoVbMcy/gDiarkZQHsejkE9aDjRHzntdrvqK00SHE1LWv1tFpC5aXBUtwDbEtw/QUVWI65mVjk4r0FdoQ3AK8x+BSRHPy3JjuS6WbLU8axZum6nFVIHzlU3K+FJtOROLH4ehnnXG5Lnqwp+Iylis1RcgyOxc=
