FROM ruby:2.3-alpine

ENV APP_HOME /app

ADD Gemfile* $APP_HOME/
WORKDIR $APP_HOME
RUN apk update \
    && apk add build-base \
    && bundle install \
    && apk del build-base \
    && rm -rf /var/cache/apk/*
ADD . $APP_HOME

ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292

CMD ["puma"]
