FROM ruby:2.3-alpine

ENV APP_HOME /app

ADD Gemfile* $APP_HOME/
WORKDIR $APP_HOME
RUN apk update \
    && apk add build-base \
    && bundle install \
    && apk del build-base \
    && rm -rf /var/cache/apk/*
ADD . $APP_HOME

ENV COMMENT_DATABASE_HOST comment_db
ENV COMMENT_DATABASE comments

CMD ["puma"]
