---
- name: Check && install python
  hosts: tag_reddit-docker-host
  become: true
  gather_facts: False
  tags: predeploy

  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
