FROM python:3.6.0-alpine

ADD . /app
WORKDIR /app

RUN apk update \
    && apk add build-base \
    && pip install -r /app/requirements.txt \
    && apk del build-base \
    && rm -rf /var/cache/apk/*

ENV POST_DATABASE_HOST post_db
ENV POST_DATABASE posts

ENTRYPOINT ["python3", "post_app.py"]
