---
- name: Prepare directories and files
  hosts: all
  become: true

  tasks:
    - name: create required directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /srv/gitlab/config
        - /srv/gitlab/data
        - /srv/gitlab/logs

    - name: put docker-compose.yml in /srv/gitlab/
      template:
        src: ../templates/docker-compose.yml.j2
        dest: /srv/gitlab/docker-compose.yml
