version: '3.3'
services:

  post_db:
    container_name: db
    image: mongo
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    container_name: ui
    image: ${USER_NAME}/ui
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - front_net

  post:
    container_name: post
    image: ${USER_NAME}/post
    networks:
      - front_net
      - back_net

  comment:
    container_name: comment
    image: ${USER_NAME}/comment
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
  front_net:
    driver: bridge
    driver_opts:
      subnet: 10.0.1.0/24
  back_net:
    driver: bridge
    driver_opts:
      subnet: 10.0.2.0/24
