Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |v|
    v.memory = 512
  end

  config.vm.define "dockerhost" do |dckr|
    dckr.vm.box = "ubuntu/xenial64"
    dckr.vm.hostname = "dockerhost"
    dckr.vm.network :private_network, ip: "10.10.10.10"

    dckr.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/docker.yml"
      ansible.extra_vars = {
        "docker_edition" => "ce",
        "docker_package" => "docker-{{ docker_edition }}",
        "docker_package_state" => "present"
      }
    end
  end
end

