groups:
  - name: alert.rules
    rules:
    - alert: InstanceDown
      expr: up == 0
      for: 1m
      labels:
        severity: page
      annotations:
        description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute'
        summary: 'Instance {{ $labels.instance }} down'
    - alert: 95_percentile
      expr: histogram_quantile(0.95, sum(rate(ui_request_response_time_bucket[5m])) by (le)) > 0.0474
      for: 10s
      labels:
        severity: page
      annotations:
        description: 'UI high responce time for 10 s'
        summary: 'UI high responce time'
