version: '3.3'
services:
  post_db:
    container_name: db
    image: mongo:${MONGO_V}
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    container_name: ui
    build: ./ui
    image: ${USERNAME}/ui:${UI_V}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - front_net
  post:
    container_name: post
    build: ./post-py
    image: ${USERNAME}/post:${POST_V}
    networks:
      - front_net
      - back_net
  comment:
    container_name: comment
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_V}
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
  front_net:
    driver: bridge
    driver_opts:
      subnet: 10.0.1.0/24
  back_net:
    driver: bridge
    driver_opts:
      subnet: 10.0.2.0/24
